name: Sync to S3 From Github Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
    
        with:
            aws-s3-bucket : ${{ secrets.AWS_S3_BUCKET }}
            aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-north-1 
            
      - name: Sync to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET }} \
          --acl public-read \
          --delete \
          --exclude '.git/*' \

